### ISSUE TITLE
sharing paper

### ISSUE THREAD

**Issue by xin71** [Vincent-Hoo/Knowledge-Distillation-for-Super-resolution#1]
Hi Vincent,

This repo seems super interesting! Would you mind sharing your paper? I would love to read it! My email is `xliu0@cs.washington.edu`. Thanks very much!

**Comment by SuckChen** [comment]
I am also looking forward to reading your paper. My email is liang2chen@stu.xmu.edu.cn. Thanks a lot in adavance.

**Comment by Vincent-Hoo** [comment]
> I am also looking forward to reading your paper. My email is [liang2chen@stu.xmu.edu.cn](mailto:liang2chen@stu.xmu.edu.cn). Thanks a lot in adavance.

I will upload my paper online soon.
