### ISSUE TITLE
class EDSR member function forward() has some bugs. 

### ISSUE THREAD

**Issue by idgmatrix** [Vincent-Hoo/Knowledge-Distillation-for-Super-resolution#2]
def forward(self, x):
        feature_maps = []
        x = self.sub_mean(x)
        x = self.head(x)
        feature_maps.append(x)

        res = self.body1(x)
        feature_maps.append(x)  <===  SHOULD BE feature_maps.append(res) 
        res = self.body2(res)
        feature_maps.append(x)  <===  SHOULD BE feature_maps.append(res)
        res = self.body3(res)
        feature_maps.append(res)
        
        res += x
        

        x = self.tail(res)
        x = self.add_mean(x)

        return feature_maps, x

**Comment by Vincent-Hoo** [comment]
Thank you! The code has been revised.

**Comment by Vincent-Hoo** [comment]
> def forward(self, x):
> feature_maps = []
> x = self.sub_mean(x)
> x = self.head(x)
> feature_maps.append(x)
> 
> ```
>     res = self.body1(x)
>     feature_maps.append(x)  <===  SHOULD BE feature_maps.append(res) 
>     res = self.body2(res)
>     feature_maps.append(x)  <===  SHOULD BE feature_maps.append(res)
>     res = self.body3(res)
>     feature_maps.append(res)
>     
>     res += x
>     
> 
>     x = self.tail(res)
>     x = self.add_mean(x)
> 
>     return feature_maps, x 
> ```

Thank you. The code has been revised.
