### ISSUE TITLE
What`s resolution of input image are FLOPs measured on?

### ISSUE THREAD

**Issue by conson0214** [Vincent-Hoo/Knowledge-Distillation-for-Super-resolution#5]
![image](https://user-images.githubusercontent.com/27390617/89165631-6a6eed80-d5ab-11ea-8537-523fe49d4b6e.png)

What`s resolution of input image for measuring FLOPs?

**Comment by Vincent-Hoo** [comment]
> ![image](https://user-images.githubusercontent.com/27390617/89165631-6a6eed80-d5ab-11ea-8537-523fe49d4b6e.png)
> 
> What`s resolution of input image for measuring FLOPs?

The resolution is 36x64x3.
