### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by caiyuanhao1998** [Vincent-Hoo/Knowledge-Distillation-for-Super-resolution#6]
同学你好，我是清华深研院MEAI2020级的同学，我对你的这份工作非常感兴趣，想follow你的工作。不知道能不能交个朋友，我们一起搞点新的东西。我之前有发过顶会的。

**Comment by caiyuanhao1998** [comment]
我的联系方式：caiyuanhao1998（微信）

**Comment by Vincent-Hoo** [comment]
> caiyuanhao1998

你好同学，你的微信号不存在，我加不了，你可以加我的：15626120921

**Comment by Vincent-Hoo** [comment]
> 同学你好，我是清华深研院MEAI2020级的同学，我对你的这份工作非常感兴趣，想follow你的工作。不知道能不能交个朋友，我们一起搞点新的东西。我之前有发过顶会的。

你好同学，你的微信号不存在，我加不了，你可以加我的，15626120921
